export const SIGNUP_STATUS = {

  WHO_ARE_YOU: 'WHO_ARE_YOU',

  PREGNANCY_SETUP: 'PREGNANCY_SETUP',

  DUE_DATE: 'DUE_DATE',

  LMP: 'LMP',

  ULTRASOUND: 'ULTRASOUND',

  ULTRASOUND_DUE_DATE: 'ULTRASOUND_DUE_DATE',

  ULTRASOUND_WEEK: 'ULTRASOUND_WEEK',

  CURRENT_WEEK: 'CURRENT_WEEK',

  PARENT_INFO: 'PARENT_INFO',

  CREATE_ACCOUNT: 'CREATE_ACCOUNT',

  SUBSCRIPTION: 'SUBSCRIPTION',

  COMPLETE: 'COMPLETE',

};